### ISSUE TITLE
배포 TODO

### ISSUE THREAD

**Issue by JuYeong0413** [JuYeong0413/lohbs-pick#27]
- [x] 도메인 구입
- [x] GA
- [x] Debug=False
- [x] STATIC_ROOT

---

- [x] Elastic IP & Route53
- [x] createsuperuser 👉 닉네임 설정해줘야함!
- [x] Google 소셜로그인 연결
- [x] 테스트 계정 만들어두기
- [ ] 로드밸런서 https 연결
