### ISSUE TITLE
2020.10.24 주영 TODO

### ISSUE THREAD

**Issue by JuYeong0413** [JuYeong0413/lohbs-pick#43]
- [x] 도메인 구입
- [x] 주문(목록, 상세보기, 생성)
- [x] 주문 생성할때 2개이상일때 수량 잘못 나오는 버그
- [ ] 템플릿
- [x] footer 서비스 소개

~~navbar 겹침 버그~~
~~배포 준비~~
