### ISSUE TITLE
2020.10.24 연진 TODO

### ISSUE THREAD

**Issue by ygk313** [JuYeong0413/lohbs-pick#44]
- [x] 컬렉션 페이지 완성하기
- [x] (컬렉션 페이지) 수정 모달 띄우기, 삭제, 공유 버튼 연결
- [x] (컬렉션 페이지) 숫자 버튼, 연결하기
- [ ] 메인페이지 수정 및 완성하기
- [x] (메인 페이지) 배너 사진 넣기
- [x] (메인 페이지) 상품 사진 넣기  
- [ ] 배포
- [ ] 상품 롭스에서 가져오기
