### ISSUE TITLE
2020.10.24 효정 TODO

### ISSUE THREAD

**Issue by khj6165** [JuYeong0413/lohbs-pick#45]
- [x] 우편번호 검색 넣기

- [x] 소설회원가입 템플릿

- [ ] 주문, 컬렉션 완성되면 캘린더에 받아오기

- [ ] 결제모듈 알아보기

- [ ] 디자인 개선

- [x] footer에 내사진 넣기
