### ISSUE TITLE
CSS TODO 

### ISSUE THREAD

**Issue by ygk313** [JuYeong0413/lohbs-pick#57]
## Products
- [x] products/main.html 호버시 + 버튼 색깔 바꾸기

## Navbar
- [x] Home 계속 주황색으로 선택 중
- [x] 로고 교체
- [x] 로그인/로그아웃/회원가입 href 태그 navbar와  색 통일 

## Account 👉 효정 진행중
- [x] 로그인 페이지
- [x] 회원가입페이지
- [x] 소셜로그인 페이지

## Main
- [x] 가운데 배너 교체 👉 연진 진행중
- [x] 쇼핑카트 사진 교체

  
## Collection
- [x] 컬렉션 수정 페이지 버튼 교체 

## Order
- [x] 주문 생성 페이지

## MyPage
- [x] 회원정보 페이지 수정

**Comment by JuYeong0413** [comment]
Account쪽은 입력폼이 비슷해서 한 사람이 맡아서 하면 될 듯
